data:
    data_path: ./datasets/raw/market_insights_overview_all_2022_02_14.csv
    categories_path: ./datasets/raw/solr_categories_all_2022_02_14.csv
logger:
    log_level: INFO
    log_file: ./log-file.log
use_gpu_if_available: no
experiment:
    tags: [market_insights]
    save_sources_to_use: [disk]
    checkpoint_save_location: ./models/0_current_model_checkpoints/
    log_model_every_n_epoch: 10
    error_metrics:
    - MASE
    - MAE
    - MSE
    - SMAPE
    - MAPE
    save_source:
        disk:
            model_save_location: ./models/
        neptune:
            project_id: sjsivertandsanderkk/Masteroppgave
model:
    model_type: global_univariate_lstm
    rng_seed: 42
    validation_model:
        placeholder: 0
    univariate_lstm:
        hyperparameter_tuning_range:
            hidden_size: [2, 100]
            number_of_layers: [1, 5]
            dropout: [0.0, 0.4]
            optimizer_name: [RMSprop]
            learning_rate: [1e-7, 1e-2]
            number_of_epochs: [5, 40]
            batch_size: [32, 32]
            input_window_size: 10
            output_window_size: 7
            multi_variable_nr: 1
            number_of_features: 1
            number_of_trials: 5000
            stateful_lstm: yes
        global_model:
            parameters_for_all_models:
                training_size: 50
                input_window_size: 10
                output_window_size: 7
                multi_variable_nr: 1
                batch_size: 32
                number_of_epochs: 40
                stateful_lstm: yes
                should_shuffle_batches: no
                optimizer_name: RMSprop
                learning_rate: 0.000522
                hidden_layer_size: 86
                dropout: 0.0192
                number_of_features: 1
                number_of_layers: 2
            datasets:
            - 12322
            - 11428
            - 11850
            - 11852
            - 273
            - 11036
            - 11213
        local_model:
            common_parameters_for_all_models:
                training_size: 50
                input_window_size: 10
                output_window_size: 7
                multi_variable_nr: 1
                batch_size: 32
                number_of_epochs: 40
                stateful_lstm: yes
                should_shuffle_batches: no
                optimizer_name: RMSprop
            model_structure: [{time_series_id: 11573, learning_rate: 0.000522, hidden_layer_size: 86, dropout: 0.0192, number_of_features: 1, number_of_layers: 2}]
    local_univariate_cnn_ae:
        common_parameters_for_all_models:
            training_size: 7
            input_window_size: 10
            output_window_size: 7
            multi_variable_nr: 1
            batch_size: 1
            number_of_epochs: 51
            optimizer_name: adam
            loss: mse
        model_structure: [{time_series_id: 2, learning_rate: 0.03, encoder: [{filters: 8, kernel_size: 3, activation: relu}, {filters: 16, kernel_size: 5}], decoder: [{filters: 8, kernel_size: 5, activation: relu}, {filters: 1, kernel_size: 3}]}]
    local_univariate_cnn_ae_lstm:
        common_parameters_for_all_models:
            should_shuffle_batches: yes
            training_size: 7
            optimizer_name: Adam
            loss: mse
            batch_size: 32
            epochs: 20
            number_of_epochs: 20
            input_window_size: 10
            output_window_size: 7
            multi_variable_nr: 1
            lstm-shared:
                input_window_size: 10
                output_window_size: 7
                multi_variable_nr: 1
                epochs: 20
        model_structure: [{time_series_id: 11573, learning_rate: 0.03, lstm: {optimizer_name: Adam, stateful_lstm: no, loss: mse, learning_rate: 0.001, hidden_layer_size: 10, dropout: 0.113, number_of_features: 1, number_of_layers: 3}, ae: {optimizer_name: Adam, loss: mse, learning_rate: 0.001, epochs: 40}, encoder: [{filters: 8, kernel_size: 3, activation: relu}, {filters: 16, kernel_size: 5}], decoder: [{filters: 8, kernel_size: 5, activation: relu}, {filters: 1, kernel_size: 3}]}]
    local_univariate_arima:
        forecast_window_size: 7
        steps_to_predict: 7
        multi_step_forecast: yes
        hyperparameter_tuning_range:
            p: [1, 10]
            d: [1, 10]
            q: [1, 16]
        metric_to_use_when_tuning: MASE
        model_structure: [{time_series_id: 11573, hyperparameters: {p: 9, d: 2, q: 11}}]
